const projects = {
  hymnal: { type: 'Creative AI / browser instrument', title: 'Hymnal Engine', summary: 'A local-first audiovisual instrument where music, reactive visuals, and transparent overlays can be composed together, performed live, and revised through specialist AI patches.', role: 'Concept, product design, interaction, implementation', tools: 'React, JavaScript, Vite, Strudel, Web Audio, Three.js, Codex', status: 'Verified local prototype', question: 'How can generative agents change a live creative system without taking authorship or control away from its performer?', artifact: 'A working browser environment with persistent scenes, live audio analysis, an independent performance output, and a permissioned SceneSpec / AgentPatch pipeline. Music, visual, and overlay specialists propose scoped changes that can be previewed, applied, or rejected.', source: 'projects/selected/hymnal-engine.md', media: 'hymnal' },
  obs: { type: 'Live systems / visual toolkit', title: 'OBS Studio', summary: 'A local control panel and library for building, previewing, and running modular livestream graphics and browser sources.', role: 'Product direction, UI, implementation', tools: 'HTML, CSS, JavaScript, Node.js, OBS Browser Sources', status: 'Working local toolkit', question: 'How can a livestream operator treat visual assets like instruments: discoverable, configurable, and ready at the moment of performance?', artifact: 'A browsable asset library with dedicated editors, widgets, overlays, and reusable source contracts. DOLLHOUSE provides the broader visual-environment layer.', source: 'projects/selected/obs-studio.md', media: 'obs' },
  drum: { type: 'Sound / Web MIDI', title: 'Polyrhythmic Drum Machine', summary: 'A browser instrument built around linked clocks, live synthesis, MIDI control, and the physical feeling of a drumhead.', role: 'Concept, sound design, interface, code', tools: 'React, TypeScript, Web Audio, Web MIDI', status: 'Thesis prototype', question: 'Can a rhythm machine make complex polyrhythm understandable through motion and touch?', artifact: 'A playable instrument with orbital clocks, swing, kick synthesis, two-click monitoring, and recording controls.', source: 'projects/selected/polyrhythmic-drum-machine.md', media: 'drum' },
  drone: { type: 'Simulation / interactive world', title: 'Drone Fields', summary: 'A deterministic browser simulation about autonomous machines, infrastructure, weather, energy, and social behavior.', role: 'Worldbuilding, systems design, implementation', tools: 'JavaScript, deterministic simulation, browser persistence', status: 'Playable prototype', question: 'What does an ecosystem look like when the actors are machines with routes, needs, and imperfect information?', artifact: 'A replayable local world with traceable state, offline snapshots, route logic, and a deliberately inspectable simulation model.', source: 'projects/selected/drone-fields.md', media: 'drone' },
  cricket: { type: 'Game / timing system', title: 'Country Cricket Waifus', summary: 'A dependency-free browser game that turns cricket’s rules and timing into a compact, illustrated two-innings contest.', role: 'Game concept, rules, interface, implementation', tools: 'HTML, CSS, JavaScript, browser game systems', status: 'Playable prototype', question: 'How much of a sport’s drama can survive when reduced to timing, risk, and a few clear choices?', artifact: 'Two innings, twelve deliveries, wickets, ball flight, fielders, team selection, and super-over logic.', source: 'projects/selected/country-cricket-waifus.md', media: 'cricket' },
  'obs-dashboard': { type: 'Live production / browser toolkit', title: 'OBS dashboard', summary: 'The operational layer behind the visual work: a local dashboard for cataloguing, previewing, editing, and launching modular OBS browser sources.', role: 'Systems design, product direction, implementation', tools: 'Node.js, HTML/CSS/JavaScript, OBS, Browser Sources', status: 'Active toolkit', question: 'How do you make a growing library of strange visual tools usable during an actual broadcast?', artifact: 'Asset families, dedicated editor routes, widgets, overlays, and a shared runtime shaped around fast local use.', source: 'projects/selected/obs-studio.md', media: 'obs' },
  bots: { type: 'Automation / community tooling', title: 'Bots + agent systems', summary: 'A body of work using bots and AI-assisted workflows to make community memory, creative coding, planning, and repetitive coordination more manageable.', role: 'Concept, prompt/system design, implementation', tools: 'Discord, Telegram, OpenClaw, JavaScript, AI coding tools', status: 'Multiple prototypes', question: 'Where can an agent carry the repetitive load while leaving judgment, tone, and trust with a person?', artifact: 'Urufu, personality-quiz and community systems, Telegram agents, and separate Three.js, Strudel, and OBS specialist bots with shared launch, status, logging, and health-check workflows.', source: 'professional-work/bots-and-agent-systems.md', media: 'bots' },
  crypto: { type: 'Product / culture / translation', title: 'Crypto + Web3', summary: 'Product, documentation, community, and cultural work across crypto projects—making unfamiliar systems legible without flattening their weirdness.', role: 'Operations, product narrative, community, documentation', tools: 'Discord, Telegram, web publishing, community research', status: 'Selected work / archive', question: 'How do you translate a speculative protocol or token economy into something people can understand, enter, and care about?', artifact: 'Approved project work includes ETH Gobblers documentation and naming, PokeGAN maps and story content, and creator onboarding for the Omakasea NFT Launchpad. Additional archive material is clearly marked for review.', source: 'professional-work/crypto-web3.md', media: 'crypto' },
  oct7: { type: 'Webmaster / release operations', title: 'Oct 7', summary: 'Freelance webmaster and digital-operations support for a wholesale agency serving independent head shops, gift shops, and music-oriented retailers.', role: 'Webmaster, workflow design, digital operations', tools: 'WordPress, Mailchimp, Canva, SSH, WP-CLI', status: 'Ongoing professional work', question: 'How can the web presence stay coherent when the underlying work is arriving through people, releases, images, and changing priorities?', artifact: 'Web materials, newsletters, sales and catalog assets, plus technical troubleshooting and cautious publishing workflows.', source: 'professional-work/oct7-webmaster.md', media: 'oct7' },
  omakasea: { type: 'Community / creative operations', title: 'Omakasea', summary: 'Progressed from Community Manager to COO at a Web3 startup, coordinating product, creative, community, education, launches, and operations for a globally distributed team.', role: 'COO / Director of Creative & Operations', tools: 'Discord, Twitter, Telegram, YouTube, documentation, SOPs, budgets', status: 'Professional experience', question: 'How do you build enough structure for a distributed, high-velocity community to move without losing its human signal?', artifact: 'Managed social publishing and real-time support, grew the Twitter account from 0 to 47,000 followers, created crypto education videos, supported creator onboarding, and built repeatable launch and operating systems.', source: 'professional-work/omakasea.md', media: 'omakasea' }
};

const dialog = document.querySelector('#project-dialog');
const fields = { type: document.querySelector('#dialog-type'), title: document.querySelector('#dialog-title'), summary: document.querySelector('#dialog-summary'), role: document.querySelector('#dialog-role'), tools: document.querySelector('#dialog-tools'), status: document.querySelector('#dialog-status'), question: document.querySelector('#dialog-question'), artifact: document.querySelector('#dialog-artifact'), source: document.querySelector('#dialog-source'), media: document.querySelector('#dialog-media') };

function openProject(key) {
  const project = projects[key];
  if (!project) return;
  fields.type.textContent = project.type;
  fields.title.textContent = project.title;
  fields.summary.textContent = project.summary;
  fields.role.textContent = project.role;
  fields.tools.textContent = project.tools;
  fields.status.textContent = project.status;
  fields.question.textContent = project.question;
  fields.artifact.textContent = project.artifact;
  fields.source.href = project.source;
  fields.media.dataset.project = project.media;
  dialog.showModal();
}

document.querySelectorAll('[data-project]').forEach((button) => button.addEventListener('click', () => openProject(button.dataset.project)));
document.querySelector('.dialog-close').addEventListener('click', () => dialog.close());
dialog.addEventListener('click', (event) => { if (event.target === dialog) dialog.close(); });
